#!/bin/bash

# STANDARD PACKAGES
browsers='chromium-browser lynx firefox'
communicators='irssi skype thunderbird'
accessories='unrar p7zip-full transmission'
graphics='gimp gthumb imagemagick simple-scan'
multimedia='clementine pulseaudio vlc spotify'
important='wget curl sshfs ssh mosh'
libraries="python python-pip"
screen='arandr screen'
remote='x2goclient'

internet="$browsers $communicators"

# FOR DEVELOPMENT
dev_repo='git git-gui meld'
dev_util='sublime-text-installer'

# NON-STANDARD REPOSITORIES
sudo add-apt-repository ppa:webupd8team/sublime-text-3
# SPOTIFY
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 94558F59
sudo sh -c 'echo "deb http://repository.spotify.com stable non-free" >> /etc/apt/sources.list.d/spotify.list'

sudo apt-get install aptitude

sudo aptitude update
sudo aptitude upgrade

# APTITUDE INSTALL
sudo aptitude install $accessories $graphics $internet $multimedia $dev_repo $dev_util $important $screen $remote

sudo ./node
sudo ./pip

mkdir ~/temp/
sudo ./download
sudo ./compile
