#!/bin/bash

# STANDARD PACKAGES
browsers='chromium-browser lynx firefox'
communicators='irssi skype thunderbird'
accessories='unrar p7zip-full transmission'
graphics='gimp gthumb imagemagick simple-scan'
multimedia='clementine pulseaudio vlc'
important='wget curl sshfs ssh mosh dropbox'
libraries="python python-pip"
screen='arandr screen'
remote='x2goclient'
java='icedtea-7-plugin openjdk-7-jre openjdk-7-jdk'
RESTRICTED='ubuntu-restricted-extras ubuntu-restricted-addons'

internet="$browsers $communicators"

# FOR DEVELOPMENT
dev_repo='git git-gui meld'


sudo aptitude update
sudo aptitude upgrade

# APTITUDE INSTALL
sudo aptitude install $accessories $graphics $internet $multimedia $dev_repo $dev_util $important $screen $remote $RESTRICTED $java

sudo ./non-standard
sudo ./node
sudo ./pip

mkdir ~/temp/
sudo ./download
sudo ./compile

rm -fr ~/temp
