#!/bin/bash

# STANDARD PACKAGES
browsers='chromium-browser links2 firefox'
communicators='irssi thunderbird'
accessories='unrar p7zip-full transmission'
graphics='gimp gthumb imagemagick simple-scan'
multimedia='clementine'
important='wget curl mosh'
libraries="python python-pip"
screen='arandr screen'
RESTRICTED='lubuntu-restricted-extras lubuntu-restricted-addons'

internet="$browsers $communicators"

# FOR DEVELOPMENT
git='git git-gui gitk meld'
svn='subversion'

xterm_colors='ncurses-term'
#Remember to set #export TERM=xterm-256color in ~/.bashrc
sudo apt-get install aptitude

sudo apt-get install aptitude -y

sudo aptitude update
sudo aptitude upgrade -y

# APTITUDE INSTALL
sudo aptitude install $accessories $graphics $internet $multimedia $git $dev_util $important $screen $remote $RESTRICTED $java $libraries -y

sudo ./non-standard
sudo ./node
sudo ./pip
sudo ./i3

mkdir ~/temp/
sudo ./download
sudo ./compile

rm -fr ~/temp

DIR=`pwd`

rm -fr $DIR
