#!/bin/bash
node_linters='jshint'
node_css='cssmin uncss'
node_dev='gulp yo bower node-theseus forever nodemon'

sudo aptitude install npm -y;
sudo npm install -g n;
sudo n stable;
sudo npm update npm -g
sudo npm install -g $node_linters $node_css $node_dev

exit