#!/bin/bash

# NON-STANDARD REPOSITORIES
# Sublime Text 3
# sublime-text-installer
sudo add-apt-repository ppa:webupd8team/sublime-text-3

# SPOTIFY
# spotify-client
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 94558F59
sudo rm -f /etc/apt/sourced.list.d/spotify.list
sudo sh -c 'echo "deb http://repository.spotify.com stable non-free" >> /etc/apt/sources.list.d/spotify.list'

# Pipelight (Silverlight for linux)
# pipelight-multi
sudo apt-add-repository ppa:pipelight/stable

# Screencloud (something like puu.sh for Linux)
# screencloud
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/olav-st/xUbuntu_14.04/ /' >> /etc/apt/sources.list.d/screencloud.list"
cd ~/tmp/
wget http://download.opensuse.org/repositories/home:olav-st/xUbuntu_14.04/Release.key
sudo apt-key add - < Release.key

sudo aptitude update;
sudo aptitude install spotify-client sublime-text-installer pipelight-multi screencloud  -y

sudo pipelight-plugin --enable silverlight